version: 1
accounts:
  - name: alice
    coins: ["200000000000tea"]
  - name: bob
    coins: ["200000000000tea"]
  - name: joe
    coins: ["200000000000tea"]
  - name: bank
    coins: ["200000000000tea"]
  - name: fauci
    coins: ["2000000tea"]
validators:
  - name: alice
    bonded: "200000000000tea"
  - name: bob
    bonded: "200000000000tea"
  - name: joe
    bonded: "200000000000tea"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: fauci
  coins: ["2tea"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "tea"
    # party:
    #   warrenList:
    #     - index: "1"
    #       apiKey: "192.168.0.1"
    #       creator: "0x"
    mint:
      params:
        mint_denom: "tea"
    staking:
      params:
        bond_denom: "tea"
        unbonding_time: "10000s"


