// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: partychain/party/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTradeOrdersRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetTradeOrdersRequest) Reset()         { *m = QueryGetTradeOrdersRequest{} }
func (m *QueryGetTradeOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTradeOrdersRequest) ProtoMessage()    {}
func (*QueryGetTradeOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{2}
}
func (m *QueryGetTradeOrdersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTradeOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTradeOrdersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTradeOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTradeOrdersRequest.Merge(m, src)
}
func (m *QueryGetTradeOrdersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTradeOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTradeOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTradeOrdersRequest proto.InternalMessageInfo

func (m *QueryGetTradeOrdersRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetTradeOrdersResponse struct {
	TradeOrders TradeOrders `protobuf:"bytes,1,opt,name=tradeOrders,proto3" json:"tradeOrders"`
}

func (m *QueryGetTradeOrdersResponse) Reset()         { *m = QueryGetTradeOrdersResponse{} }
func (m *QueryGetTradeOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTradeOrdersResponse) ProtoMessage()    {}
func (*QueryGetTradeOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{3}
}
func (m *QueryGetTradeOrdersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTradeOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTradeOrdersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTradeOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTradeOrdersResponse.Merge(m, src)
}
func (m *QueryGetTradeOrdersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTradeOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTradeOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTradeOrdersResponse proto.InternalMessageInfo

func (m *QueryGetTradeOrdersResponse) GetTradeOrders() TradeOrders {
	if m != nil {
		return m.TradeOrders
	}
	return TradeOrders{}
}

type QueryAllTradeOrdersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTradeOrdersRequest) Reset()         { *m = QueryAllTradeOrdersRequest{} }
func (m *QueryAllTradeOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTradeOrdersRequest) ProtoMessage()    {}
func (*QueryAllTradeOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{4}
}
func (m *QueryAllTradeOrdersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTradeOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTradeOrdersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTradeOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTradeOrdersRequest.Merge(m, src)
}
func (m *QueryAllTradeOrdersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTradeOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTradeOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTradeOrdersRequest proto.InternalMessageInfo

func (m *QueryAllTradeOrdersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTradeOrdersResponse struct {
	TradeOrders []TradeOrders       `protobuf:"bytes,1,rep,name=tradeOrders,proto3" json:"tradeOrders"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTradeOrdersResponse) Reset()         { *m = QueryAllTradeOrdersResponse{} }
func (m *QueryAllTradeOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTradeOrdersResponse) ProtoMessage()    {}
func (*QueryAllTradeOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{5}
}
func (m *QueryAllTradeOrdersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTradeOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTradeOrdersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTradeOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTradeOrdersResponse.Merge(m, src)
}
func (m *QueryAllTradeOrdersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTradeOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTradeOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTradeOrdersResponse proto.InternalMessageInfo

func (m *QueryAllTradeOrdersResponse) GetTradeOrders() []TradeOrders {
	if m != nil {
		return m.TradeOrders
	}
	return nil
}

func (m *QueryAllTradeOrdersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPendingOrdersRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetPendingOrdersRequest) Reset()         { *m = QueryGetPendingOrdersRequest{} }
func (m *QueryGetPendingOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingOrdersRequest) ProtoMessage()    {}
func (*QueryGetPendingOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{6}
}
func (m *QueryGetPendingOrdersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingOrdersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingOrdersRequest.Merge(m, src)
}
func (m *QueryGetPendingOrdersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingOrdersRequest proto.InternalMessageInfo

func (m *QueryGetPendingOrdersRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetPendingOrdersResponse struct {
	PendingOrders PendingOrders `protobuf:"bytes,1,opt,name=pendingOrders,proto3" json:"pendingOrders"`
}

func (m *QueryGetPendingOrdersResponse) Reset()         { *m = QueryGetPendingOrdersResponse{} }
func (m *QueryGetPendingOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingOrdersResponse) ProtoMessage()    {}
func (*QueryGetPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{7}
}
func (m *QueryGetPendingOrdersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingOrdersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingOrdersResponse.Merge(m, src)
}
func (m *QueryGetPendingOrdersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingOrdersResponse proto.InternalMessageInfo

func (m *QueryGetPendingOrdersResponse) GetPendingOrders() PendingOrders {
	if m != nil {
		return m.PendingOrders
	}
	return PendingOrders{}
}

type QueryAllPendingOrdersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPendingOrdersRequest) Reset()         { *m = QueryAllPendingOrdersRequest{} }
func (m *QueryAllPendingOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPendingOrdersRequest) ProtoMessage()    {}
func (*QueryAllPendingOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{8}
}
func (m *QueryAllPendingOrdersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPendingOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPendingOrdersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPendingOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPendingOrdersRequest.Merge(m, src)
}
func (m *QueryAllPendingOrdersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPendingOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPendingOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPendingOrdersRequest proto.InternalMessageInfo

func (m *QueryAllPendingOrdersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPendingOrdersResponse struct {
	PendingOrders []PendingOrders     `protobuf:"bytes,1,rep,name=pendingOrders,proto3" json:"pendingOrders"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPendingOrdersResponse) Reset()         { *m = QueryAllPendingOrdersResponse{} }
func (m *QueryAllPendingOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPendingOrdersResponse) ProtoMessage()    {}
func (*QueryAllPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a437dd0de395f054, []int{9}
}
func (m *QueryAllPendingOrdersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPendingOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPendingOrdersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPendingOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPendingOrdersResponse.Merge(m, src)
}
func (m *QueryAllPendingOrdersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPendingOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPendingOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPendingOrdersResponse proto.InternalMessageInfo

func (m *QueryAllPendingOrdersResponse) GetPendingOrders() []PendingOrders {
	if m != nil {
		return m.PendingOrders
	}
	return nil
}

func (m *QueryAllPendingOrdersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "teapartycrypto.partychain.party.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "teapartycrypto.partychain.party.QueryParamsResponse")
	proto.RegisterType((*QueryGetTradeOrdersRequest)(nil), "teapartycrypto.partychain.party.QueryGetTradeOrdersRequest")
	proto.RegisterType((*QueryGetTradeOrdersResponse)(nil), "teapartycrypto.partychain.party.QueryGetTradeOrdersResponse")
	proto.RegisterType((*QueryAllTradeOrdersRequest)(nil), "teapartycrypto.partychain.party.QueryAllTradeOrdersRequest")
	proto.RegisterType((*QueryAllTradeOrdersResponse)(nil), "teapartycrypto.partychain.party.QueryAllTradeOrdersResponse")
	proto.RegisterType((*QueryGetPendingOrdersRequest)(nil), "teapartycrypto.partychain.party.QueryGetPendingOrdersRequest")
	proto.RegisterType((*QueryGetPendingOrdersResponse)(nil), "teapartycrypto.partychain.party.QueryGetPendingOrdersResponse")
	proto.RegisterType((*QueryAllPendingOrdersRequest)(nil), "teapartycrypto.partychain.party.QueryAllPendingOrdersRequest")
	proto.RegisterType((*QueryAllPendingOrdersResponse)(nil), "teapartycrypto.partychain.party.QueryAllPendingOrdersResponse")
}

func init() { proto.RegisterFile("partychain/party/query.proto", fileDescriptor_a437dd0de395f054) }

var fileDescriptor_a437dd0de395f054 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0xad, 0xad, 0x38, 0xa1, 0x22, 0x63, 0x0e, 0xb2, 0xa6, 0x5b, 0x59, 0xd1, 0xaa,
	0xe8, 0x0e, 0x49, 0x5b, 0x82, 0x68, 0x94, 0x54, 0xb4, 0x17, 0xc1, 0x18, 0x72, 0x2a, 0x82, 0x4c,
	0x92, 0x71, 0xbb, 0xb0, 0xd9, 0xd9, 0xee, 0x4e, 0xa4, 0xa1, 0x78, 0xf1, 0x13, 0x08, 0x7e, 0x05,
	0x3f, 0x86, 0x27, 0x11, 0x2c, 0x5e, 0x2c, 0x78, 0xf1, 0x20, 0x22, 0x89, 0x1f, 0x44, 0x76, 0x66,
	0x62, 0x76, 0xcd, 0xc6, 0xdd, 0xd4, 0xdc, 0xb6, 0xbb, 0xef, 0x9f, 0xdf, 0x33, 0xcf, 0x3b, 0x6f,
	0x03, 0x8b, 0x1e, 0xf1, 0x79, 0xbf, 0xbd, 0x47, 0x6c, 0x17, 0x8b, 0x47, 0xbc, 0xdf, 0xa3, 0x7e,
	0xdf, 0xf4, 0x7c, 0xc6, 0x19, 0x5a, 0xe3, 0x94, 0xc8, 0x00, 0xbf, 0xef, 0x71, 0x66, 0x8e, 0x83,
	0xe5, 0xa3, 0x56, 0xb0, 0x98, 0xc5, 0x44, 0x2c, 0x0e, 0x9f, 0x64, 0x9a, 0x56, 0xb4, 0x18, 0xb3,
	0x1c, 0x8a, 0x89, 0x67, 0x63, 0xe2, 0xba, 0x8c, 0x13, 0x6e, 0x33, 0x37, 0x50, 0x5f, 0x6f, 0xb4,
	0x59, 0xd0, 0x65, 0x01, 0x6e, 0x91, 0x80, 0xca, 0x6e, 0xf8, 0x65, 0xa9, 0x45, 0x39, 0x29, 0x61,
	0x8f, 0x58, 0xb6, 0x2b, 0x82, 0x55, 0xec, 0xea, 0x04, 0x9e, 0x47, 0x7c, 0xd2, 0x1d, 0x95, 0xba,
	0x3c, 0xf1, 0x99, 0xfb, 0xa4, 0x43, 0x9f, 0x33, 0xbf, 0x43, 0xfd, 0x51, 0xd0, 0x95, 0xc9, 0x1a,
	0xd4, 0xed, 0xd8, 0xae, 0x15, 0x0b, 0x33, 0x0a, 0x10, 0x3d, 0x0d, 0x61, 0xea, 0xa2, 0x41, 0x83,
	0xee, 0xf7, 0x68, 0xc0, 0x8d, 0x67, 0xf0, 0x7c, 0xec, 0x6d, 0xe0, 0x31, 0x37, 0xa0, 0xe8, 0x21,
	0x5c, 0x96, 0x20, 0x17, 0xc0, 0x25, 0x70, 0x2d, 0x5f, 0x5e, 0x37, 0x53, 0x4e, 0xca, 0x94, 0x05,
	0xb6, 0x4f, 0x1d, 0xfd, 0x58, 0xcb, 0x35, 0x54, 0xb2, 0x51, 0x86, 0x9a, 0xa8, 0xbe, 0x43, 0x79,
	0x33, 0x04, 0x7f, 0x22, 0x80, 0x54, 0x6f, 0x54, 0x80, 0x4b, 0xb6, 0xdb, 0xa1, 0x07, 0xa2, 0xc7,
	0x99, 0x86, 0xfc, 0xc3, 0x08, 0xe0, 0xc5, 0xc4, 0x1c, 0x45, 0xd6, 0x84, 0x79, 0x3e, 0x7e, 0xad,
	0xf0, 0x6e, 0xa6, 0xe2, 0x45, 0x4a, 0x29, 0xc6, 0x68, 0x19, 0xa3, 0xa3, 0x40, 0x6b, 0x8e, 0x93,
	0x00, 0xfa, 0x08, 0xc2, 0xb1, 0x73, 0xaa, 0xe5, 0x55, 0x53, 0xda, 0x6c, 0x86, 0x36, 0x9b, 0x72,
	0xa8, 0x94, 0xcd, 0x66, 0x9d, 0x58, 0x54, 0xe5, 0x36, 0x22, 0x99, 0xc6, 0x7b, 0xa0, 0xb4, 0xfd,
	0xdd, 0x66, 0x9a, 0xb6, 0xc5, 0x39, 0x68, 0x43, 0x3b, 0x31, 0xfa, 0x05, 0xe5, 0x67, 0x1a, 0xbd,
	0x44, 0x8a, 0xe1, 0x6f, 0xc2, 0xe2, 0xc8, 0x99, 0xba, 0x9c, 0xb0, 0x2c, 0x7e, 0x1e, 0xc2, 0xd5,
	0x29, 0x59, 0x4a, 0xf5, 0x2e, 0x5c, 0xf1, 0xa2, 0x1f, 0xd4, 0x01, 0x9b, 0xe9, 0x23, 0x17, 0xcd,
	0x52, 0xca, 0xe3, 0xa5, 0x8c, 0x17, 0x0a, 0xb9, 0xe6, 0x38, 0x89, 0xc8, 0xf3, 0x72, 0xf6, 0x23,
	0x50, 0x2a, 0x27, 0x1b, 0x4d, 0x57, 0xb9, 0x38, 0x27, 0x95, 0x73, 0x73, 0xb8, 0xfc, 0xfd, 0x34,
	0x5c, 0x12, 0x32, 0xd0, 0x3b, 0x00, 0x97, 0xe5, 0x95, 0x46, 0x1b, 0xa9, 0x88, 0x93, 0x7b, 0x45,
	0xdb, 0x9c, 0x2d, 0x49, 0xb2, 0x18, 0xf8, 0xf5, 0xd7, 0x5f, 0x6f, 0x17, 0xae, 0xa3, 0x75, 0xdc,
	0xa4, 0xa4, 0x1e, 0x86, 0x3d, 0x10, 0xd9, 0x78, 0xca, 0x9a, 0x44, 0x9f, 0x00, 0xcc, 0x47, 0xc6,
	0x1f, 0xdd, 0xc9, 0xd6, 0x36, 0x71, 0x1f, 0x69, 0x77, 0x4f, 0x96, 0xac, 0xd8, 0xab, 0x82, 0xbd,
	0x82, 0xb6, 0x52, 0xd9, 0xa3, 0x3b, 0x1c, 0x1f, 0x8a, 0x5b, 0xf2, 0x0a, 0x7d, 0x00, 0xf0, 0x6c,
	0xa4, 0x6c, 0xcd, 0x71, 0xb2, 0x8a, 0x49, 0xdc, 0x59, 0x59, 0xc5, 0x24, 0x6f, 0x22, 0x63, 0x4b,
	0x88, 0xc1, 0xe8, 0xd6, 0x4c, 0x62, 0xd0, 0x17, 0x00, 0x57, 0x62, 0xf3, 0x8a, 0xaa, 0x99, 0xcf,
	0x34, 0xe9, 0x7e, 0x6a, 0xf7, 0x4e, 0x9a, 0xae, 0x74, 0xdc, 0x17, 0x3a, 0x6e, 0xa3, 0x4a, 0xfa,
	0x40, 0xc5, 0xfe, 0x67, 0xfe, 0xb1, 0xe5, 0x33, 0x80, 0xe7, 0x62, 0xa5, 0x43, 0x63, 0xaa, 0x99,
	0xcf, 0xf6, 0x7f, 0x44, 0x4d, 0x5b, 0x25, 0x46, 0x45, 0x88, 0x2a, 0x21, 0x3c, 0xa3, 0xa8, 0xed,
	0xc7, 0x47, 0x03, 0x1d, 0x1c, 0x0f, 0x74, 0xf0, 0x73, 0xa0, 0x83, 0x37, 0x43, 0x3d, 0x77, 0x3c,
	0xd4, 0x73, 0xdf, 0x86, 0x7a, 0x6e, 0xb7, 0x6c, 0xd9, 0x7c, 0xaf, 0xd7, 0x32, 0xdb, 0xac, 0xfb,
	0x8f, 0xa2, 0x07, 0x23, 0xcf, 0xfb, 0x1e, 0x0d, 0x5a, 0xcb, 0xe2, 0x77, 0xc5, 0xc6, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xae, 0xe7, 0x0d, 0x59, 0x63, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a TradeOrders by index.
	TradeOrders(ctx context.Context, in *QueryGetTradeOrdersRequest, opts ...grpc.CallOption) (*QueryGetTradeOrdersResponse, error)
	// Queries a list of TradeOrders items.
	TradeOrdersAll(ctx context.Context, in *QueryAllTradeOrdersRequest, opts ...grpc.CallOption) (*QueryAllTradeOrdersResponse, error)
	// Queries a PendingOrders by index.
	PendingOrders(ctx context.Context, in *QueryGetPendingOrdersRequest, opts ...grpc.CallOption) (*QueryGetPendingOrdersResponse, error)
	// Queries a list of PendingOrders items.
	PendingOrdersAll(ctx context.Context, in *QueryAllPendingOrdersRequest, opts ...grpc.CallOption) (*QueryAllPendingOrdersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/teapartycrypto.partychain.party.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TradeOrders(ctx context.Context, in *QueryGetTradeOrdersRequest, opts ...grpc.CallOption) (*QueryGetTradeOrdersResponse, error) {
	out := new(QueryGetTradeOrdersResponse)
	err := c.cc.Invoke(ctx, "/teapartycrypto.partychain.party.Query/TradeOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TradeOrdersAll(ctx context.Context, in *QueryAllTradeOrdersRequest, opts ...grpc.CallOption) (*QueryAllTradeOrdersResponse, error) {
	out := new(QueryAllTradeOrdersResponse)
	err := c.cc.Invoke(ctx, "/teapartycrypto.partychain.party.Query/TradeOrdersAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingOrders(ctx context.Context, in *QueryGetPendingOrdersRequest, opts ...grpc.CallOption) (*QueryGetPendingOrdersResponse, error) {
	out := new(QueryGetPendingOrdersResponse)
	err := c.cc.Invoke(ctx, "/teapartycrypto.partychain.party.Query/PendingOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingOrdersAll(ctx context.Context, in *QueryAllPendingOrdersRequest, opts ...grpc.CallOption) (*QueryAllPendingOrdersResponse, error) {
	out := new(QueryAllPendingOrdersResponse)
	err := c.cc.Invoke(ctx, "/teapartycrypto.partychain.party.Query/PendingOrdersAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a TradeOrders by index.
	TradeOrders(context.Context, *QueryGetTradeOrdersRequest) (*QueryGetTradeOrdersResponse, error)
	// Queries a list of TradeOrders items.
	TradeOrdersAll(context.Context, *QueryAllTradeOrdersRequest) (*QueryAllTradeOrdersResponse, error)
	// Queries a PendingOrders by index.
	PendingOrders(context.Context, *QueryGetPendingOrdersRequest) (*QueryGetPendingOrdersResponse, error)
	// Queries a list of PendingOrders items.
	PendingOrdersAll(context.Context, *QueryAllPendingOrdersRequest) (*QueryAllPendingOrdersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TradeOrders(ctx context.Context, req *QueryGetTradeOrdersRequest) (*QueryGetTradeOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeOrders not implemented")
}
func (*UnimplementedQueryServer) TradeOrdersAll(ctx context.Context, req *QueryAllTradeOrdersRequest) (*QueryAllTradeOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeOrdersAll not implemented")
}
func (*UnimplementedQueryServer) PendingOrders(ctx context.Context, req *QueryGetPendingOrdersRequest) (*QueryGetPendingOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingOrders not implemented")
}
func (*UnimplementedQueryServer) PendingOrdersAll(ctx context.Context, req *QueryAllPendingOrdersRequest) (*QueryAllPendingOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingOrdersAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teapartycrypto.partychain.party.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TradeOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTradeOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TradeOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teapartycrypto.partychain.party.Query/TradeOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TradeOrders(ctx, req.(*QueryGetTradeOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TradeOrdersAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTradeOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TradeOrdersAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teapartycrypto.partychain.party.Query/TradeOrdersAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TradeOrdersAll(ctx, req.(*QueryAllTradeOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teapartycrypto.partychain.party.Query/PendingOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingOrders(ctx, req.(*QueryGetPendingOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingOrdersAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPendingOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingOrdersAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teapartycrypto.partychain.party.Query/PendingOrdersAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingOrdersAll(ctx, req.(*QueryAllPendingOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teapartycrypto.partychain.party.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TradeOrders",
			Handler:    _Query_TradeOrders_Handler,
		},
		{
			MethodName: "TradeOrdersAll",
			Handler:    _Query_TradeOrdersAll_Handler,
		},
		{
			MethodName: "PendingOrders",
			Handler:    _Query_PendingOrders_Handler,
		},
		{
			MethodName: "PendingOrdersAll",
			Handler:    _Query_PendingOrdersAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partychain/party/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTradeOrdersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTradeOrdersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTradeOrdersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTradeOrdersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTradeOrdersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTradeOrdersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TradeOrders.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTradeOrdersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTradeOrdersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTradeOrdersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTradeOrdersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTradeOrdersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTradeOrdersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TradeOrders) > 0 {
		for iNdEx := len(m.TradeOrders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TradeOrders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingOrdersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingOrdersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingOrdersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingOrdersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingOrdersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingOrdersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PendingOrders.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPendingOrdersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPendingOrdersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPendingOrdersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPendingOrdersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPendingOrdersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPendingOrdersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PendingOrders) > 0 {
		for iNdEx := len(m.PendingOrders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingOrders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTradeOrdersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTradeOrdersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TradeOrders.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTradeOrdersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTradeOrdersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TradeOrders) > 0 {
		for _, e := range m.TradeOrders {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPendingOrdersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPendingOrdersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PendingOrders.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPendingOrdersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPendingOrdersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PendingOrders) > 0 {
		for _, e := range m.PendingOrders {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTradeOrdersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTradeOrdersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTradeOrdersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTradeOrdersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTradeOrdersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTradeOrdersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TradeOrders.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTradeOrdersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTradeOrdersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTradeOrdersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTradeOrdersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTradeOrdersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTradeOrdersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeOrders = append(m.TradeOrders, TradeOrders{})
			if err := m.TradeOrders[len(m.TradeOrders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingOrdersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingOrdersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingOrdersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingOrdersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingOrdersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingOrdersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingOrders.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPendingOrdersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPendingOrdersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPendingOrdersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPendingOrdersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPendingOrdersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPendingOrdersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingOrders = append(m.PendingOrders, PendingOrders{})
			if err := m.PendingOrders[len(m.PendingOrders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
